#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Display Wallpaper
feh --bg-fill ~/Documents/Wallpaper/wallpaper-dark.png &

# X Composite Manager
picom &

# Status Bar
dte(){
	dte="$(date +" %A, %B %d -  %I:%M %p")"
	echo -e "$dte"
}

wfi(){
	wfi="$(iw dev wlan0 info | grep ssid | awk '{print $2}')"
	
	if [ -z "$wfi" ];
	then
		echo -e " Disconnected"
	else
		echo -e " $wfi"
	fi
}

while true; do
	xsetroot -name "[ $(printf '\x01') ] $(wfi) | $(dte) |"
	sleep 5s
done &	

# Execute DWM
exec dwm
